pipeline {
    agent {
        label 'agent-1'
    }

    environment { 
        appVersion = ''
        REGION = "us-east-1"
        ACC_ID = "913524900812"
        PROJECT = "roboshop"
    }

    options {
        timeout(time: 30, unit: 'MINUTES') 
        disableConcurrentBuilds()
        ansiColor('xterm')
    }

    stages {
        stage('init') {
            steps {
                script {
                    withAWS(credentials: 'aws-cred', region: 'us-east-1') {
                        sh """
                            cd 10_sg
                            terraform init -reconfigure
                        """
                    }
                }
            }
        }

        stage('plan') {
            steps {
                script {
                    withAWS(credentials: 'aws-cred', region: 'us-east-1') {
                        sh """
                            cd 10_sg
                            terraform plan
                        """
                    }
                }
            }
        }

        stage('apply') {
            input {
                message "Should we continue?"
                ok "Yes, we should."
                submitter "alice,bob"
            }
            steps {
                script {
                    withAWS(credentials: 'aws-cred', region: 'us-east-1') {
                        sh """
                            cd 10_sg
                            terraform apply -auto-approve
                        """
                    }
                }
            }
        }
    }   // 👈 this was missing earlier!

    post { 
        always { 
            echo 'I will always say Hello again!'
            deleteDir()
        }
        success { 
            echo 'Hello Success'
        }
        failure { 
            echo 'Hello Failure'
        }
    }
}
