pipeline{
    agent {
        label 'agent-1'
    }
    environment{
        app_version = ''
        REGION = 'us-east-1'
        ACC_ID = '913524900812'
        PROJECT = 'roboshop'
    }
    options{
        timeout(time: 30, unit: 'MINUTES') 
        disableConcurrentBuilds()
        ansiColor('xterm')
    }
    stages{
        stage(init){
            steps {
                script {
                    withAWS(credentials: 'aws-cred',region: 'us-east-1')
                    sh """
                      cd 01_vpc
                      terraform init -reconfigure
                    """
                }
            }
        }
        stage(plan){
            steps{
                script{
                    withAWS(credentials: 'aws-cred',region: 'us-east-1')
                    sh """
                      cd 01_vpc
                      terraform plan
                    """

                }
            }
        }
        stage(apply){
            input{
                message "Should we continue?"
                ok "Yes, we should."
                submitter "alice,bob"
            }
            steps{
                script{
                    withAWS(credentials: 'aws-cred',region: 'us-east-1')
                    sh """
                      cd 01_vpc
                      terraform apply -auto-approve
                    """
                }
            }
        }
        stage('Trigger SG'){
            steps{
                script{
                    build job: '10_SG'
                    propagate: 'false'
                    wait: 'true'
                }
            }
        }
        post{
            always{
                echo 'I will always say Hello again!'
            deleteDir()
            }
            sucess{
                echo 'Hello success'
            }
            failure{
                echo 'Hello Failure'
            }
        }
        
    }
}