pipeline {
    agent  {
        label 'agent-1'
    }
    environment { 
        appVersion = ''
        REGION = "us-east-1"
        ACC_ID = "913524900812"
        PROJECT = "roboshop"
    }
    options {
        timeout(time: 30, unit: 'MINUTES') 
        disableConcurrentBuilds()
        ansiColor('xterm')
    }
    /* parameters {
        string(name: 'PERSON', defaultValue: 'Mr Jenkins', description: 'Who should I say hello to?')
        text(name: 'BIOGRAPHY', defaultValue: '', description: 'Enter some information about the person')
        booleanParam(name: 'TOGGLE', defaultValue: true, description: 'Toggle this value')
        choice(name: 'CHOICE', choices: ['One', 'Two', 'Three'], description: 'Pick something')
        password(name: 'PASSWORD', defaultValue: 'SECRET', description: 'Enter a password') 
    } */
    // Build
    stages {
        stage('init') {
            steps {
                script {
                    withAWS(credentials: 'aws-cred', region: 'us-east-1') {
                        sh """
                            cd 10_sg
                            terraform init -reconfigure
                        """
                    }
                }
            }
        }

        stage('plan') {
            steps {
                script {
                    withAWS(credentials: 'aws-cred', region: 'us-east-1') {
                        sh """
                            cd 10_sg
                            terraform plan
                        """
                    }
                }
            }
        }
        stage('apply') {
            input {
                message "Should we continue?"
                ok "Yes, we should."
                submitter "alice,bob"
            }
            steps {
                script {
                    withAWS(credentials: 'aws-cred', region: 'us-east-1') {
                        sh """
                            cd 10_sg
                            terraform apply -auto-approve
                        """
                    }
                }
            }
        }
        stage('Bastion','ACM','EKS') {
            parllel {
                stage('trigger Bastion') {
                    steps {
                        script {
                            build Job: '20_bastion'
                            propagate: false
                            wait: true

                        }
                    }
                }
                stage ('Triger EKS') {
                    steps{
                        script{
                            build Job: '80_eks'
                            propagate: false
                            wait: false
                        }
                    }
                }
                stage('triger acm'){
                    steps{
                        script{
                            build Job: '60-acm'
                            propagate: false
                            wait: false
                            
                        }
                    }
                }
            }
        }   
    }

    post { 
        always { 
            echo 'I will always say Hello again!'
            deleteDir()
        }
        success { 
            echo 'Hello Success'
        }
        failure { 
            echo 'Hello Failure'
        }
    }
}